server:
  port: 8091

spring:
  application:
    name: service-one

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

config-server:
  address: http://localhost:8090
service-two:
  address: http://localhost:8092

graphite:
  address: 127.0.0.1:2003
