eureka:
  instance:
    hostname: apigateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  zipkin:
    baseUrl: http://zipkin:9411

zuul:
  routes:
    service-one:
      url: http://one:8092
    service-two:
      url: http://two:8093
