server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:db
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoint:
    health:
      show-details: always
