version: "3.9"
services:
  person-app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - keycloak

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: keycloak
      KEYCLOAK_HTTP_PORT: 8100
    command:
      - "-Djboss.http.port=8100"
    ports:
      - "8100:8100"
