server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:db
  jpa:
    hibernate:
      ddl-auto: none

keycloak:
  realm: person-app
  auth-server-url: http://keycloak:8100/auth
  ssl-required: external
  resource: person-app
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: asGDf31CcEtUcGGAwHjwZGAQwe2ffIssF
